# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# HELP:
# 1. To update versions automatically, run: 'pre-commit autoupdate' (in Terminal)
# 2. To skip any particular check (say pylint), run: 'SKIP=pylint pre-commit run --all-files'

default_language_version:
  python: python3.11
default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
        args: ["--maxkb=512"]
      - id: check-symlinks
      - id: requirements-txt-fixer
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args: ["--branch=main"]
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.3
    hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell

  - repo: local
    hooks:
      - id: mypy
        name: mypy (poetry)
        entry: poetry run mypy
        language: system
        types: [python]
        pass_filenames: true

  - repo: local
    hooks:
      - id: pylint
        name: pylint (poetry)
        entry: poetry run pylint -j 0 --fail-under=10
        language: system
        types: [python]